/**
 * Scam detection heuristic patterns derived from:
 * - SmishX (USENIX SOUPS 2025) SMS phishing indicators
 * - Smishtank phishing SMS dataset categories
 * - NICE Actimize & Sumsub 2025 fraud pattern reports
 *
 * Each pattern includes a weighted score (1-16) reflecting confidence
 * that the pattern indicates scam activity when present in SMS context.
 */

const PATTERNS = [
  // ─── URGENCY & PRESSURE ──────────────────────────────────────────
  {
    regex: /\b(act|respond|reply|click|call|pay)\s+(now|immediately|right\s*away|today|asap|at\s*once)\b/i,
    score: 12,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Pressure to act immediately',
    description: 'Scam messages pressure you to act quickly so you don\'t have time to think critically or verify the claim.',
  },
  {
    regex: /\b(urgent|emergency|critical)\s*(action|notice|alert|message|update|warning|matter|request)\b/i,
    score: 10,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Urgency language',
    description: 'Words like "urgent" and "emergency" are commonly used in scams to create panic.',
  },
  {
    regex: /\b(expires?|expiring|expiration)\s+(today|tonight|soon|in\s*\d+\s*(hours?|minutes?|days?|hrs?|mins?))\b/i,
    score: 11,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Artificial deadline',
    description: 'Fake deadlines are a manipulation tactic to rush you into acting without verification.',
  },
  {
    regex: /\b(limited\s*time|only\s*\d+\s*(left|remaining)|last\s*chance|final\s*(notice|warning|reminder|attempt))\b/i,
    score: 10,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Artificial scarcity',
    description: 'Claims of "limited time" or "last chance" create false urgency to manipulate your decisions.',
  },
  {
    regex: /\b(account|service|access|subscription|membership)\s+(will\s+be|is\s+being|has\s+been|will\s+get)\s+(suspended|closed|terminated|deactivated|locked|disabled|restricted|cancell?ed|deleted|frozen)\b/i,
    score: 14,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Account suspension threat',
    description: 'Threatening to suspend or lock your account is one of the most common phishing tactics.',
  },
  {
    regex: /\bwithin\s+\d+\s*(hours?|minutes?|days?|hrs?|mins?)\b/i,
    score: 6,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Short time constraint',
    description: 'Imposing a short deadline prevents you from verifying the claim through official channels.',
  },
  {
    regex: /\b(don'?t\s+(ignore|miss|delay|wait)|must\s+(respond|act|verify|confirm|update|pay)|failure\s+to\s+(respond|act|pay|verify|comply))\b/i,
    score: 9,
    category: 'Urgency & Pressure',
    categoryKey: 'urgency',
    label: 'Coercive instruction',
    description: 'Telling you what you "must" do or not to "ignore" is a pressure tactic to override your judgment.',
  },

  // ─── FINANCIAL / PAYMENT ─────────────────────────────────────────
  {
    regex: /\b(pay(ment)?|fee|charge|balance|amount|dues?)\s+(due|owed|outstanding|required|overdue|unpaid|pending)\b/i,
    score: 13,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Payment demand',
    description: 'Demands for payment via text are rarely legitimate. Always verify through the organization\'s official website.',
  },
  {
    regex: /\b(gift\s*cards?|wire\s*transfer|bitcoin|crypto(currency)?|western\s*union|money\s*order|money\s*gram|cash\s*app|zelle|venmo|apple\s*pay)\b/i,
    score: 16,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Unusual payment method',
    description: 'Legitimate organizations never ask for payment via gift cards, cryptocurrency, or peer-to-peer apps.',
  },
  {
    regex: /\b(unpaid|overdue|outstanding|delinquent)\s+(toll|bill|balance|invoice|fine|fee|tax|debt|payment)\b/i,
    score: 14,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Unpaid balance claim',
    description: 'Fake notifications about unpaid bills or tolls are among the most common SMS scam types.',
  },
  {
    regex: /\b(bank|credit\s*card|debit\s*card|routing)\s*(number|info|detail|credential|account)\b/i,
    score: 15,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Banking information request',
    description: 'No legitimate entity will ask for your banking details via text message.',
  },
  {
    regex: /\$\s*\d+[\d,.]*\b/,
    score: 4,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Specific dollar amount',
    description: 'Including a specific dollar amount makes the scam feel more convincing and real.',
  },
  {
    regex: /\b(refund|reimburse(ment)?|cashback|rebate)\b/i,
    score: 8,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Refund or rebate lure',
    description: 'Fake refund offers are used to trick you into providing financial information.',
  },
  {
    regex: /\b(penalty|penalties|additional\s*(charge|fee)|late\s*(fee|charge|penalty)|surcharge)\b/i,
    score: 10,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Penalty or late fee threat',
    description: 'Threatening penalties or late fees creates pressure to pay quickly without verification.',
  },
  {
    regex: /\b(settle\s+(now|your|this|the)|pay\s*here|make\s*a?\s*payment|complete\s*payment|process\s*payment)\b/i,
    score: 8,
    category: 'Financial Request',
    categoryKey: 'financial',
    label: 'Payment action prompt',
    description: 'Direct prompts to "settle" or "make a payment" through a text link are highly suspicious.',
  },

  // ─── PERSONAL INFORMATION ────────────────────────────────────────
  {
    regex: /\b(verify|confirm|validate|update|provide|submit)\s+(your|ur|the)\s*(account|identity|information|info|details|credentials|profile)\b/i,
    score: 13,
    category: 'Personal Information',
    categoryKey: 'personal_info',
    label: 'Request to verify personal information',
    description: 'Requests to "verify" or "update" your account info via text are a hallmark of phishing.',
  },
  {
    regex: /\b(social\s*security|ssn|password|passcode|pin\s*(number|code)?|login\s*(credentials?|info|details)|one[- ]?time\s*(code|password|passcode)|otp)\b/i,
    score: 16,
    category: 'Personal Information',
    categoryKey: 'personal_info',
    label: 'Sensitive credential request',
    description: 'Requests for passwords, PINs, SSNs, or one-time codes are a major red flag. Legitimate services never ask for these via text.',
  },
  {
    regex: /\b(enter|input|type|provide|send\s+us)\s+(your|ur)\b/i,
    score: 7,
    category: 'Personal Information',
    categoryKey: 'personal_info',
    label: 'Direct data request',
    description: 'Direct requests for your information via text are suspicious, especially from unknown senders.',
  },
  {
    regex: /\b(click\s+(here|below|the\s+link)|tap\s+(here|below|the\s+link)|follow\s+the\s+link|visit\s+the\s+link)\s*(to\s+)?(verify|confirm|update|secure|restore|unlock|reactivate)\b/i,
    score: 12,
    category: 'Personal Information',
    categoryKey: 'personal_info',
    label: 'Link to verify or update',
    description: 'Messages asking you to click a link to verify your account are classic phishing attempts.',
  },

  // ─── SUSPICIOUS URLs ─────────────────────────────────────────────
  {
    regex: /https?:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/,
    score: 14,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'IP address URL',
    description: 'URLs using raw IP addresses instead of domain names commonly hide malicious destinations.',
  },
  {
    regex: /\b(bit\.ly|tinyurl\.com|t\.co|goo\.gl|ow\.ly|is\.gd|buff\.ly|adf\.ly|tiny\.cc|shorte\.st|cutt\.ly|rb\.gy)\b/i,
    score: 8,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'URL shortener detected',
    description: 'Shortened URLs hide the real destination and are commonly used in phishing messages.',
  },
  {
    regex: /https?:\/\/[^\s]*\.(tk|ml|ga|cf|gq|xyz|top|buzz|club|work|click|link|surf|rest|fit|cam|icu|monster|sbs|cfd)\b/i,
    score: 11,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'Suspicious domain extension',
    description: 'Free or cheap domain extensions like .tk, .xyz, and .top are frequently used for phishing sites.',
  },
  {
    regex: /https?:\/\/[^\s]*[a-z]+-[a-z]+-[a-z]+\.[a-z]/i,
    score: 8,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'Multi-hyphenated domain',
    description: 'Domains with multiple hyphens often impersonate legitimate brands (e.g., "usps-delivery-update.tk").',
  },
  {
    regex: /https?:\/\/[^\s]*?(paypa[l1i]|amaz[o0]n|app[l1i]e|goog[l1i]e|faceb[o0]{2}k|micr[o0]s[o0]ft|netf[l1i]ix|we[l1i]{2}s.?farg[o0]|ch[a@]se)[^\s]*\.[a-z]/i,
    score: 14,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'Brand impersonation in URL',
    description: 'The URL contains a variation of a known brand name, a common technique to mimic legitimate websites.',
  },
  {
    regex: /https?:\/\/[^\s]+/i,
    score: 3,
    category: 'Suspicious URL',
    categoryKey: 'url',
    label: 'Contains a link',
    description: 'Links in unsolicited messages should be treated with caution, especially from unknown senders.',
  },

  // ─── IMPERSONATION ───────────────────────────────────────────────
  {
    regex: /\b(usps|ups|fedex|dhl|postal\s*service|united\s*parcel)\b/i,
    score: 6,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Delivery service reference',
    description: 'Scammers frequently impersonate delivery services. Verify through the carrier\'s official app or website.',
  },
  {
    regex: /\b(package|parcel|shipment|delivery)\s*(can\s*not|cannot|could\s*not|couldn'?t|was\s*not|wasn'?t)\s*(be\s*)?(delivered|completed|processed)\b/i,
    score: 12,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Failed delivery claim',
    description: 'Package delivery scams are among the most common smishing attacks. Real carriers use their official apps.',
  },
  {
    regex: /\b(irs|internal\s*revenue|tax\s*(authority|agency|bureau|department)|social\s*security\s*administration|ssa|government|federal\s*agency)\b/i,
    score: 13,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Government agency impersonation',
    description: 'Government agencies like the IRS and SSA never initiate contact or make demands via text message.',
  },
  {
    regex: /\b(wells?\s*fargo|chase|bank\s*of\s*america|citibank|citi\s*bank|capital\s*one|td\s*bank|us\s*bank|pnc|truist)\b/i,
    score: 10,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Bank name reference',
    description: 'Scammers impersonate well-known banks. Always verify through your banking app or official website.',
  },
  {
    regex: /\b(apple|microsoft|google|amazon|walmart|target|costco)\s*(support|security|account|team|alert|id)?\s*:?\s*(alert|warning|notice|verify|suspended|compromised|security|unauthorized)\b/i,
    score: 11,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Tech or retail company impersonation',
    description: 'Major companies don\'t send unsolicited security alerts via text.',
  },
  {
    regex: /\b(netflix|hulu|disney\s*\+?|spotify|prime\s*video|hbo|streaming)\b.*\b(cancel|suspend|expire|billing|payment|renew)\b/i,
    score: 10,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Streaming service impersonation',
    description: 'Streaming services handle billing through their apps and websites, not via text messages.',
  },
  {
    regex: /\b(ez[- ]?pass|sun\s*pass|fast\s*track|i[- ]?pass|toll\s*(authority|road|agency|plaza|service))\b/i,
    score: 12,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Toll service impersonation',
    description: 'Toll payment scams have surged recently. Real toll agencies send notices by mail, not text.',
  },
  {
    regex: /\b(dear\s+(customer|user|member|client|sir|ma'?am|valued\s+(customer|member|user))|dear\s+account\s*holder)\b/i,
    score: 7,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Generic greeting',
    description: 'Generic greetings like "Dear Customer" indicate the sender doesn\'t actually know who you are.',
  },
  {
    regex: /\b(security\s*(team|department|center|division|alert)|fraud\s*(team|department|center|division|alert|protection))\b/i,
    score: 10,
    category: 'Impersonation',
    categoryKey: 'impersonation',
    label: 'Security department claim',
    description: 'Claims of being from a "security team" or "fraud department" are used to appear authoritative.',
  },

  // ─── THREATS & INTIMIDATION ──────────────────────────────────────
  {
    regex: /\b(legal\s*(action|proceedings?|consequences?)|lawsuit|prosecution|prosecuted|sued|court\s*order)\b/i,
    score: 13,
    category: 'Threats & Intimidation',
    categoryKey: 'threat',
    label: 'Legal action threat',
    description: 'Threats of legal action via text are almost always scams. Real legal proceedings use formal written notice.',
  },
  {
    regex: /\b(arrest(ed)?|warrant|police|authorities|law\s*enforcement|detained)\b/i,
    score: 14,
    category: 'Threats & Intimidation',
    categoryKey: 'threat',
    label: 'Arrest or law enforcement threat',
    description: 'Law enforcement never threatens arrest via text message. This is a fear-based manipulation tactic.',
  },
  {
    regex: /\b(account\s*(compromised|hacked|breached|at\s*risk)|unauthorized\s*(access|activity|transaction|login|charge))\b/i,
    score: 12,
    category: 'Threats & Intimidation',
    categoryKey: 'threat',
    label: 'Account compromise claim',
    description: 'Claims that your account was "compromised" create fear to push you into acting without thinking.',
  },
  {
    regex: /\b(device\s*(has\s*been\s*)?(infected|hacked|compromised)|virus\s*(detected|found)|malware)\b/i,
    score: 13,
    category: 'Threats & Intimidation',
    categoryKey: 'threat',
    label: 'Device compromise claim',
    description: 'Notifications about device infections via text are fake. Real security software uses its own interface.',
  },
  {
    regex: /\b(will\s+result\s+in|consequences?\s+include|you\s+will\s+(face|be\s+subject\s+to)|we\s+will\s+be\s+forced\s+to)\b/i,
    score: 9,
    category: 'Threats & Intimidation',
    categoryKey: 'threat',
    label: 'Consequence threat',
    description: 'Vague threats of consequences are designed to make you act out of fear rather than reason.',
  },

  // ─── PRIZES & REWARDS ────────────────────────────────────────────
  {
    regex: /\b(congratulations|congrats)[!.]?\s*(you('ve|\s+have)\s*(been\s*)?(selected|chosen|won|awarded))/i,
    score: 14,
    category: 'Prizes & Rewards',
    categoryKey: 'reward',
    label: 'Prize notification',
    description: 'Unsolicited "congratulations, you\'ve won" messages are one of the oldest and most common scam types.',
  },
  {
    regex: /\byou('ve|\s+have)\s*(won|been\s+awarded|been\s+selected\s+for)\s/i,
    score: 12,
    category: 'Prizes & Rewards',
    categoryKey: 'reward',
    label: 'Winning claim',
    description: 'You cannot win a prize from a contest you never entered. These are invariably scams.',
  },
  {
    regex: /\b(claim\s+(now|your|the|this|it)|redeem\s+(now|your|the|this)|collect\s+(now|your|the|this))\b/i,
    score: 10,
    category: 'Prizes & Rewards',
    categoryKey: 'reward',
    label: 'Redemption prompt',
    description: 'Prompts to "claim" or "redeem" a prize are designed to lure you to a malicious website.',
  },
  {
    regex: /\b(lottery|sweepstakes?|drawing|raffle|jackpot|grand\s*prize)\b/i,
    score: 13,
    category: 'Prizes & Rewards',
    categoryKey: 'reward',
    label: 'Lottery or sweepstakes mention',
    description: 'Legitimate lotteries and sweepstakes never notify winners via unsolicited text message.',
  },
  {
    regex: /\b(free\s+(gift|iphone|phone|laptop|money|cash|trip|vacation|cruise)|exclusive\s+(offer|deal|reward)|special\s+(promotion|offer|deal))\b/i,
    score: 9,
    category: 'Prizes & Rewards',
    categoryKey: 'reward',
    label: 'Free gift or exclusive offer',
    description: 'Offers of free high-value items or "exclusive" deals via text are lures to collect your information.',
  },
];

module.exports = { PATTERNS };
